version: "3"
services:
  chrome:
    image: selenium/node-chrome
    shm_size: '2g'
    depends_on:
      - selenium_hub
    environment:
      - SE_EVENT_BUS_HOST=selenium_hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_NO_PASSWORD=1

  firefox:
    image: selenium/node-firefox
    shm_size: '2g'
    depends_on:
      - selenium_hub
    environment:
      - SE_EVENT_BUS_HOST=selenium_hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_NO_PASSWORD=1

  selenium_hub:
    image: selenium/hub:latest
    container_name: selenium_hub
    ports:
      - '4442:4442'
      - '4443:4443'
      - '4444:4444'
      - '7900:7900'