version: "3"
services:
  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    privileged: true
    shm_size: '2g'
    ports:
      - 4444:4444
      - 7900:7900
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_VNC_NO_PASSWORD=1

